### ISSUE TITLE
write-cert-and-key-in-separate-files defaulting to true?

### ISSUE THREAD

**Issue by ivanalfonso-msft** [Azure/secrets-store-csi-driver-provider-azure#1075]
Hello, we had an issue because CSI driver suddenly (after updating it to 1.4) started creating the cert and key file in addition to the single file, I didn't look at the code in details, but it appears to me the intension was for this to be disabled by default, however it created the new files for us without us setting the new flag.

Any help would be appreciated. Thanks

**Comment by nilekhc** [comment]
Hi, @ivanalfonso-msft Thanks for opening an issue.

The default behavior is set to false. https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/621209ce915186328ca35751950dc87164521ff9/charts/csi-secrets-store-provider-azure/values.yaml#L178


How are you installing the provider?

**Comment by DrewRomanyk** [comment]
@nilekhc For me it is being set to true when it is being installed by the AKS addon, I dont see any documentation on how to change the setting for `write-cert-and-key-in-separate-files` or `construct-pem-chain`

**Comment by ivanalfonso-msft** [comment]
For me, when we got upgraded to https://github.com/Azure/AKS/releases/tag/2023-01-22 , it came with the flag enabled.

**Comment by nilekhc** [comment]
> @nilekhc For me it is being set to true when it is being installed by the AKS addon, I dont see any documentation on how to change the setting for `write-cert-and-key-in-separate-files` or `construct-pem-chain`

@ZeroMagic has anything changed in AKS add-on?

cc @aramase

**Comment by aramase** [comment]
AFAIK, for the AKS add-on since these configuration parameters can't be exposed as flags, they are enabled by default when the change is backward compatible. The `write-cert-and-key-in-separate-files` creates the individual cert and key file in addition to the single file (which always existed). So it hasn't altered the default behavior.

@ivanalfonso-msft what is the issue you're facing the new files being written?
