### ISSUE TITLE
Sample Ingress steps leads to tls.crt 0 bytes

### ISSUE THREAD

**Issue by zicaden** [Azure/secrets-store-csi-driver-provider-azure#190]
Hello Team,

I followed the steps as specified here https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/sample/ingress-controller-tls

I am using a single pem file that contains both public and private key as depicted in the example with 

    objectName: ingresscert
          objectType: secret

  data: 
    - objectName: ingresscert
      key: tls.key
    - objectName: ingresscert
      key: tls.crt

when i describe secret i see the following. This is leading to default ssl fake certificate being passed on tests

Name:         ingress-tls-csi
Namespace:    ingress
Labels:       <none>
Annotations:  <none>

Type:  kubernetes.io/tls

Data
====
tls.crt:  0 bytes
tls.key:  62 bytes

I also did a openssl verify on the pem file in the mounted secret store and found the data to be valid.

I can do a separate crt and key from akv, but wondering the cause of the issue.

Any ideas?

**Comment by aramase** [comment]
@zicaden How are you importing the cert in to Key Vault? I followed the doc and I was able to get `tls.crt` and `tls.key`.

1. Generated the crt and key using openssl command in the doc
2. Created a single PEM file that contains both the private key and the certificate
3. Imported the pem file by running - `az keyvault certificate import -n pemtls --vault-name kindkv -f tls.pem`
4. Setup the rest of the steps in the doc to create SecretProviderClass and other pods

I see the secret created fine with `tls.crt` and `tls.key`

```
➜ kubectl get secret ingress-tls-csi -n ingress-test
NAME              TYPE                DATA   AGE
ingress-tls-csi   kubernetes.io/tls   2      3m9s
```

Are you uploading the pem file as a certificate?

**Comment by zicaden** [comment]
I am using the following:

az keyvault secret set --name NAME-OF-SECRET --vault-name NAME-OF-VAULT --encoding base64 --file filename.pem

the pem file has both private key and the certificate

**Comment by aramase** [comment]
> az keyvault secret set --name NAME-OF-SECRET --vault-name NAME-OF-VAULT --encoding base64 --file filename.pem

If setting the certificate content as a secret, then the driver assumes this to just be a secret as there is no `KeyID` and sets the content in mount as is. It doesn't decode the secret, which means it's written to the mount in the base64 encoded format as it was uploaded. The driver requires the files to be in PEM format to get the keys and certs from to write as k8s tls secret. The Key Vault provider converts to PEM format when it detects the secret is a part of a certificate. If you upload the pem/pfx certs as secrets, Key Vault in the background will split the contents and save the private key as a secret, public key as key and certificate. Is there a reason for uploading the file as a secret instead of it's actual type cert?

**Comment by zicaden** [comment]
Hello thank you for the note. I guess i misinterpreted the documentation - where the pem file must be of type secret and hence did the above. I followed the step you provided and imported as a certificate and it is working now.
