### ISSUE TITLE
mounter.SetUpAt failed to get CSI client: driver name   secrets-store.csi.k8s.io not found in the list of registered CSI drivers

### ISSUE THREAD

**Issue by lukepaceBJ** [Azure/secrets-store-csi-driver-provider-azure#346]
**What steps did you take and what happened:**
Followed the steps from here: https://medium.com/faun/how-to-use-secrets-from-azure-key-vault-in-azure-kubernetes-service-704973be5fc1

Also tried these: https://docs.microsoft.com/en-us/azure/key-vault/general/key-vault-integrate-kubernetes

**What did you expect to happen:**
Pod is created with mounted secrets volume.

**Anything else you would like to add:**
I am running an AKS cluster with two node pools one Linux (v 1.18.10) and and one Windows (v. 1.18.10). I am using a service principal that was created during cluster creation. SP was set to has permission to read secrets and keys.

**Which access mode did you use to access the Azure Key Vault instance:**
[e.g. Service Principal, Pod Identity, User Assigned Managed Identity, System Assigned Managed Identity]
Service Principal

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): **0.0.17**
- Azure Key Vault provider version: (use the image tag): **0.0.11**
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.10", GitCommit:"62876fc6d93e891aa7fbe19771e6a6c03773b0f7", GitTreeState:"clean", BuildDate:"2020-10-16T20:43:34Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by aramase** [comment]
@lukepaceBJ

1. Is the application running on windows node?
    - If yes, have you deployed the CSI driver and AKV provider on the windows node with the helm configuration values? [Ref doc](https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure#configuration)
2. Are the CSI driver and AKV provider pods running on all the nodes? The driver and provider are deployed as daemonsets and need to be run on all nodes. If the driver pod isn't running on the node application is running, then you'll see the `driver name secrets-store.csi.k8s.io not found in the list of registered CSI drivers` error.

**Comment by lukepaceBJ** [comment]
1. The application is running on windows. How should windows.enabled be included in the helm install?
2. CSI driver and AKV provider are only running on Linux nodes. Sounds like installing with windows enabled should allow driver and provider to run on the windows nodes.

**Comment by aramase** [comment]
You can enable the driver and provider for windows by running 

```
helm install csi csi-secrets-store-provider-azure/csi-secrets-store-provider-azure --set windows.enabled=true --set secrets-store-csi-driver.windows.enabled=true
```

The supported helm configurations are documented here: https://github.com/Azure/secrets-store-csi-driver-provider-azure/tree/master/charts/csi-secrets-store-provider-azure#configuration

**Comment by lukepaceBJ** [comment]
That seemed to solve one the problem. Now looks like an issue with nodePublishSecretRef of in the declaration of my volume mount. I was referencing this issue https://github.com/Azure/secrets-store-csi-driver-provider-azure/issues/127 but keep getting the below when deploying pod:

MountVolume.SetUp failed for volume "secrets-store01-inline" : rpc error: code
  = Unknown desc = failed to mount secrets store objects for pod
  default/windows-secrets-store-inline-pod, err: rpc error: code = Unknown desc
  = failed to mount objects, error: failed to yaml unmarshal objects, error:
  yaml: line 56: did not find expected '-' indicator

**Comment by aramase** [comment]
@lukepaceBJ that looks like an error in the `objects` array in the `SecretProviderClass`. This is a sample `SecretProviderClass`: https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/master/examples/v1alpha1_secretproviderclass_service_principal.yaml.

Please check that the yaml is valid similar to the one I posted. Also, the line number 56 in `SecretProviderClass` is the erroneous definition.

**Comment by aramase** [comment]
@lukepaceBJ Is the issue resolved now?

**Comment by lukepaceBJ** [comment]
I am still having an issue when mounting the volume (summarizing) :

failed to mount objects, error: failed to get objectType:secret, objectName:sitecore-adminpassword, objectVersion::azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token
Original Error: adal: Refresh request failed. Status Code =
  '401'. Response body:
  {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client
  secret is provided.

**Comment by aramase** [comment]
@lukepaceBJ The client secret seems to be invalid. If you're using the service principal auth method, please check the client ID and client secret used while creating the Kubernetes secret are correct and valid.

**Comment by aramase** [comment]
@lukepaceBJ Were you able to fix the `clientsecret` and try it out?

**Comment by lukepaceBJ** [comment]
Yes. This ticket can be closed. Thank you

**Comment by aramase** [comment]
@lukepaceBJ Thank you for the confirmation. 

Closing this issue. Please feel free to reopen if you have any questions.

**Comment by shayc12** [comment]
Hello,
I have used a security script that on my test aks cluster verifies NSA Hardening for k8s, we have the following issues:

`[control: Allow privilege escalation] failed 
Description: Attackers may gain access to a container and uplift its privilege to enable excessive capabilities.
Failed:
   Namespace kube-csi
      Deployment - aad-pod-identity-mic
      DaemonSet - aad-pod-identity-nmi
Remediation: If your application does not need it, make sure the allowPrivilegeEscalation field of the securityContext is set to false.
 
[control: Allowed hostPath] failed 
Description: Mounting host directory to the container can be abused to get access to sensitive data and gain persistence on the host machine.
Failed:
   Namespace kube-csi
      DaemonSet - aad-pod-identity-nmi
      DaemonSet - csi-csi-secrets-store-provider-azure
Remediation: Refrain from using host path mount.
  
[control: Automatic mapping of service account] failed 
Description: Potential attacker may gain access to a POD and steal its service account token. Therefore, it is recommended to disable automatic mapping of the service account tokens in service account configuration and enable it only for PODs that need to use them.
Failed:
   Namespace kube-csi
      ServiceAccount - aad-pod-identity-mic
      ServiceAccount - aad-pod-identity-nmi
      ServiceAccount - csi-secrets-store-provider-azure
      ServiceAccount - secrets-store-csi-driver
   
Remediation: Disable automatic mounting of service account tokens to PODs either at the service account level or at the individual POD level, by specifying the automountServiceAccountToken: false. Note that POD level takes precedence.
 
[control: Immutable container filesystem] failed 
Description: Mutable container filesystem can be abused to inject malicious code or data into containers. Use immutable (read-only) filesystem to limit potential attacks.
Failed:
   Namespace kube-csi
      Deployment - aad-pod-identity-mic
      DaemonSet - secrets-store-csi-driver
 
Remediation: Set the filesystem of the container to read-only when possible (POD securityContext, readOnlyRootFilesystem: true). If containers application needs to write into the filesystem, it is recommended to mount secondary filesystems for specific directories where application require write access.
 
[control: Ingress and Egress blocked] failed 
Description: Disable Ingress and Egress traffic on all pods wherever possible. It is recommended to define restrictive network policy on all new PODs, and then enable sources/destinations that this POD must communicate with.
Failed:
   Namespace kube-csi
      Deployment - aad-pod-identity-mic
      DaemonSet - csi-csi-secrets-store-provider-azure
      DaemonSet - secrets-store-csi-driver
Remediation: Define a network policy that restricts ingress and egress connections.
 

[control: Linux hardening] failed 
Description: Containers may be given more privileges than they actually need. This can increase the potential impact of a container compromise.
Failed:
   Namespace kube-csi
      Deployment - aad-pod-identity-mic
      DaemonSet - secrets-store-csi-driver
Remediation: You can use AppArmor, Seccomp, SELinux and Linux Capabilities mechanisms to restrict containers abilities to utilize unwanted privileges.


 
[control: Privileged container] failed 
Description: Potential attackers may gain access to privileged containers and inherit access to the host resources. Therefore, it is not recommended to deploy privileged containers unless it is absolutely necessary. This control identifies all the privileged Pods.
Failed:
   Namespace kube-csi
      DaemonSet - secrets-store-csi-driver
Remediation: Remove privileged capabilities by setting the securityContext.privileged to false. If you must deploy a Pod as privileged, add other restriction to it, such as network policy, Seccomp etc and still remove all unnecessary capabilities. Use the exception mechanism to remove unnecessary notifocations.
 
 
[control: hostNetwork access] failed 
Description: Potential attackers may gain access to a POD and inherit access to the entire host network. For example, in AWS case, they will have access to the entire VPC. This control identifies all the PODs with host network access enabled.
Failed:
   Namespace kube-csi
      DaemonSet - aad-pod-identity-nmi
      DaemonSet - csi-csi-secrets-store-provider-azure
Remediation: Only connect PODs to host network when it is necessary. If not, set the hostNetwork field of the pod spec to false, or completely remove it (false is the default). Whitelist only those PODs that must have access to host network by design.
 
NSA FRAMEWORK`

My question is if I were implemented it is it will effect Azure AKS management and may effect the cluster usage ?
