### ISSUE TITLE
kubernetes-keyvault-flexvol vs secrets-store-csi-driver-provider-azure

### ISSUE THREAD

**Issue by aelmanaa** [Azure/secrets-store-csi-driver-provider-azure#63]
Hello,

thank you for this project. Just got few questions:

1. Is  kubernetes-keyvault-flexvol being depcreated for this project?
1.  Does this project contain all the functionalities of kubernetes-keyvault-flexvol + the following bug fixes/enhancements?
1.  Can we already use this project in production?  or we have to stick with kubernetes-keyvault-flexvol for a while?

thanks a lot

**Comment by ritazh** [comment]
Thanks for the question @aelmanaa 

> Is kubernetes-keyvault-flexvol being depcreated for this project?

Yes. As flexvol is getting deprecated in Kubernetes, we are deprecating kubernetes-keyvault-flexvol in favor of secrets-store-csi-driver-provider-azure.

> Does this project contain all the functionalities of kubernetes-keyvault-flexvol + the following bug fixes/enhancements?

Yes. As soon as we have completed feature parity, we will add the `deprecated` label to the  kubernetes-keyvault-flexvol  project readme. Please expect this to happen some time this week.

> Can we already use this project in production? or we have to stick with kubernetes-keyvault-flexvol for a while?

Since this project is still relatively new and requires users to migrate their existing solutions from flexvol to csi, I would advise to test this in dev and staging before running it in production.

cc @phillipgibson

**Comment by HoussemDellai** [comment]
Thank you for the answer.
I think this should be mentioned on kubernetes-keyvault-flexvol github page !

**Comment by ritazh** [comment]
Closed via https://github.com/Azure/kubernetes-keyvault-flexvol/pull/191 Added deprecation message to kubernetes-keyvault-flexvol project README.
