### ISSUE TITLE
RunAsNonRootUser

### ISSUE THREAD

**Issue by yktd26** [Azure/secrets-store-csi-driver-provider-azure#652]
**Describe the solution you'd like**
csi driver pods are ran with root

**Anything else you would like to add:**
AKS security reports that the pods in our cluster are running with root user. And we find that csi driver is ran with root.
Is it possible to run the csi driver pods with non root user?

**Environment:**

- Secrets Store CSI Driver version: (use the image tag):
- Azure Key Vault provider version: (use the image tag):
- Kubernetes version: (use `kubectl version`):
- Cluster type: (e.g. AKS, aks-engine, etc):

**Comment by nilekhc** [comment]
@yktd26 Thanks for opening the issue. The driver pod need to run as root in order to mount the volume as tmpfs in pod. We recommend installing driver and provider in `kube-system` namespace.

Please refer to *Why kube-system* section in the [doc](https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/installation/) for additional information.

**Comment by yktd26** [comment]
@nilekhc thank you a lot, closing it.
