### ISSUE TITLE
Secret does not get updated

### ISSUE THREAD

**Issue by simon-an** [Azure/secrets-store-csi-driver-provider-azure#746]
**What steps did you take and what happened:**
I use a secret provider class to sync kubernetes secrets from the mounted volume to environment variables.
This works fine, initially. 
But when adding new secrets to the Keyvault, updating the SecretProviderClass and the Deployment, the secrets are not patched to the kubernetes secret.

**What did you expect to happen:**
Adding keys to and existing secret must work.

**Anything else you would like to add:**
A workaround is, to delete the entire deployment and the secret.

**Which access mode did you use to access the Azure Key Vault instance:**
User Assigned Managed Identity

**Environment:**

- Secrets Store CSI Driver version: mcr.microsoft.com/oss/kubernetes-csi/secrets-store/driver:v1.0.0
- Azure Key Vault provider version: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.0.0-rc.0
- Kubernetes version:  v1.22.2  Ubuntu 18.04.6 LTS   5.4.0-1062-azure
- Cluster type: AKS

**Comment by JawnnyB** [comment]
You'll want to ensure that you've enabled SecretRotation and the rotationPollInterval.  For example if deploying as a Helm chart:

--set secrets-store-csi-driver.enableSecretRotation=true
--set secrets-store-csi-driver.rotationPollInterval=30m

When secrets are added or updated in Keyvault they will be patched into the kubernetes secret when the csi driver next polls Keyvault based on the value you've provided. 

Keep in mind that even once the secret is patched into kubernetes the new secrets or updated values will not be available as environment variables in pods already running.  There is no connection from a running pod back to Keyvault since the volume mount takes place on pod restart.

Best method I've found to update, is a rollout restart for the namespace.  This creates new secretproviderclass pods for every deployment and updates all pods to use the latest kubernetes secret values in the mounted volume.  Have not noticed any loss of availability either since the new pods are created prior to terminating those already running.  

kubectl rollout restart deploy -n {namespace}

**Comment by aramase** [comment]
Thanks for adding the details @JawnnyB!

As mentioned, enabling secret rotation will update the volume mount and kubernetes secret with the latest/new values. If the feature isn't enabled, here are the steps for the new secret to be added to the pod and kubernetes secret: https://secrets-store-csi-driver.sigs.k8s.io/known-limitations.html#mounted-content-and-kubernetes-secret-not-updated

**Comment by NikhilRajNR** [comment]
Is there any update on this issue? We have same issue after upgrading from 0.0.6 to 1.0.0. having same environment and cluster.

**Comment by aramase** [comment]
> Is there any update on this issue? We have same issue after upgrading from 0.0.6 to 1.0.0. having same environment and cluster.

@NikhilRajNR What is the issue you're seeing? This issue is specific to the enable secret rotation feature not being enabled. If you have the feature enabled and aren't seeing the mounted content updated with new values, please provide your environment information, scenario and relevant logs.

Here is a link to the troubleshooting guide: https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/

**Comment by NikhilRajNR** [comment]
> > Is there any update on this issue? We have same issue after upgrading from 0.0.6 to 1.0.0. having same environment and cluster.
> 
> @NikhilRajNR What is the issue you're seeing? This issue is specific to the enable secret rotation feature not being enabled. If you have the feature enabled and aren't seeing the mounted content updated with new values, please provide your environment information, scenario and relevant logs.
> 
> Here is a link to the troubleshooting guide: https://azure.github.io/secrets-store-csi-driver-provider-azure/troubleshooting/

We have enabled secret rotation feature. But secret is not getting updated. Although after restart pods getting Mount location secret updated. But to get secret updated we have to delete secret and then restart the pod.

**Comment by aramase** [comment]
> We have enabled secret rotation feature. But secret is not getting updated. Although after restart pods getting Mount location secret updated. But to get secret updated we have to delete secret and then restart the pod running with nginx image.

Please create a new github issue and provide the following:

1. Installation commands used
2. Driver and provider version
3. `SecretProviderClass` yaml
4. `Pod` yaml
