### ISSUE TITLE
deployment/provider-azure-installer.yaml in tag v1.0.0 has image: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.0.0-rc.0

### ISSUE THREAD

**Issue by deyanp** [Azure/secrets-store-csi-driver-provider-azure#750]
Deployment/provider-azure-installer.yaml in tag v1.0.0 has image: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.0.0-rc.0, but should be v1.0.0 instead ..

**Comment by nilekhc** [comment]
Thanks for opening issue @deyanp 

I can see correct image tag in [deployment yaml file](https://github.com/Azure/secrets-store-csi-driver-provider-azure/blob/a40f8978a9532701b0023d08f9dd94eb1ee32f01/deployment/provider-azure-installer.yaml#L27).

**Comment by nilekhc** [comment]
I see. It appears that we inadvertently miss this change in our release. We are releasing v1.0.1 this week.

**Comment by aramase** [comment]
Thanks for reporting the issue.

The diff in the tag should only be the image `v1.0.0-rc.0` instead of `v1.0.0`. The tag was accidentally performed against `main` instead of the release branch.

The helm install will use the current image for the chart version `1.0.0`

We've published `v1.0.1` release which should be tagged to the correct branch. Please do let us know if you run into any issues with the new release.

**Comment by deyanp** [comment]
thanks, @aramase , all good with v1.0.1!
