### ISSUE TITLE
Secret not syncing after pod restarts

### ISSUE THREAD

**Issue by AalimahG** [Azure/secrets-store-csi-driver-provider-azure#821]
**Have you**

I'm using AKS version 1.22.6 with csi secret store addon enabled.
Despite this fact , the secret doesn't get updated when a change is done on the key vault and the pod restarted.

**What steps did you take and what happened:**
- Create secret class provider
- create pod
- update value on key vault
- restart the pod
**What did you expect to happen:**

Value changed on the secret manifest
**Anything else you would like to add:**
AKS is using version 0.0.15 of csi-secret-store

**Which access mode did you use to access the Azure Key Vault instance:**
Pod Identity created by default while enabling feature with az aks enable-addons

**Environment:**

- Secrets Store CSI Driver version: (use the image tag): 0.0.22
- Azure Key Vault provider version: (use the image tag): 0.0.15
- Kubernetes version: (use `kubectl version` and `kubectl get nodes -o wide`): 1.22.6
- Cluster type: (e.g. AKS, aks-engine, etc): AKS

**Comment by nilekhc** [comment]
Hi @AalimahG Thanks for opening an issue.

Is autorotation enabled on the addon? 
https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#enable-and-disable-autorotation

Also, 0.0.15 is a very old version. Since then we have stable 1.0.0 released. Could you try to disable and enable add-on again?
